version: '3'

volumes:
  ikev2-vpn-data:

services:
  vpn:
    image: hwdsl2/vpn-ipsec-server
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: vpn-ipsec-server
    container_name: vpn-ipsec-server
    volumes:
      - ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
